{application,scenic_driver_nerves_rpi,
             [{applications,[kernel,stdlib,elixir,scenic]},
              {description,"Scenic.Driver.Nerves.Rpi - Scenic driver providing drawing (only) on a Raspberry Pi under Nerves.\n"},
              {modules,['Elixir.Scenic.Driver.Nerves.Rpi',
                        'Elixir.Scenic.Driver.Nerves.Rpi.Cache',
                        'Elixir.Scenic.Driver.Nerves.Rpi.Compile',
                        'Elixir.Scenic.Driver.Nerves.Rpi.Font',
                        'Elixir.Scenic.Driver.Nerves.Rpi.Graph',
                        'Elixir.Scenic.Driver.Nerves.Rpi.Input',
                        'Elixir.Scenic.Driver.Nerves.Rpi.Port']},
              {registered,[]},
              {vsn,"0.10.0"}]}.
