{application,nerves_init_gadget,
             [{applications,[kernel,stdlib,elixir,logger,ring_logger,mdns,
                             nerves_runtime,nerves_firmware_ssh,one_dhcpd,
                             nerves_network,nerves_time]},
              {description,"Simple initialization for devices running Nerves\n"},
              {modules,['Elixir.Nerves.InitGadget',
                        'Elixir.Nerves.InitGadget.Application',
                        'Elixir.Nerves.InitGadget.NetworkManager',
                        'Elixir.Nerves.InitGadget.NetworkManager.State',
                        'Elixir.Nerves.InitGadget.Options',
                        'Elixir.Nerves.InitGadget.SSHConsole']},
              {registered,[]},
              {vsn,"0.7.0"},
              {mod,{'Elixir.Nerves.InitGadget.Application',[]}}]}.
